name: ecomm
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    flutter_staggered_grid_view: ^0.4.0
    cupertino_icons: ^1.0.2
    flutter_slidable: ^3.0.1
    audioplayers: ^5.2.1
    cloud_firestore: ^4.14.0
  # google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/4.png
    - assets/5.png
    - assets/6.png
